"""
Database package for AlgoX Track
"""

from .models import (
    get_db_connection,
    init_db,
    add_problem,
    add_attempt,
    get_all_problems,
    get_user_attempts,
    get_topic_distribution,
    get_difficulty_distribution,
    get_weekly_progress,
    get_leaderboard,
    get_leaderboard_page,
    get_user_stats,
    get_today_stats,
    get_today_solved_problems,
    search_problems,
    update_user_stats,
    get_user,
    register_user,
    login_user,
    update_username,
    update_email,
    update_password,
)

__all__ = [
    'get_db_connection',
    'init_db',
    'add_problem',
    'add_attempt',
    'get_all_problems',
    'get_user_attempts',
    'get_topic_distribution',
    'get_difficulty_distribution',
    'get_weekly_progress',
    'get_leaderboard',
    'get_leaderboard_page',
    'get_user_stats',
    'get_today_stats',
    'get_today_solved_problems',
    'search_problems',
    'update_user_stats',
    'get_user',
    'register_user',
    'login_user',
    'update_username',
    'update_email',
    'update_password',
]
